language: node_js
node_js:
- 10.9.0
cache: npm
before_install:
- ls -la
notifications:
  slack:
    secure: QFYzgyBRHgKIyhcSiaU4hws9qdDXa2k5ppENNdcV1vsCVtgU0/jFykt5ydv6JOHznec8aK3ulKErWnkPyaCVa6JYcIPZfB8qseVv2YsswZc5ZcKWn639DRfLpUqAGq/kGssJTu0fZ8SPzDZLESX9u378AKZExkM6eV4qZ+MrVobL4CUdtK86kJ9eEG6O0CpQqqz5WGjnvaJa8TNPhFge7vSipYbt+1ue+ztEgBKlUppLIKJ6S9GlOeHqVT7PODwdxfVCbBM/NfgvxyqGXhQYyTGbY4NGd14qWnhtK8e6xmmhdhcpxaIh/+DXCCzfJstIChxe6tfdI6/gxlyuPuoDZSik34IEBhYTIOJkOovgU9DenxAFMYnsBAJG6rGTVp/o6wImQFFtceCUJsPt9kQnAN6T2Xq8Kz2zh2G8U3+g1Q/tWEJa5mx8aH16SJfi0Hq/5PjTWJGlaXnleiDTNO7tm0WGZalWhF/LbQpqsOftT6zk63pVQe5ivkcIjpl4iAraIxMHIl7sl9oZJNfDehXHNABYMxV7A6Dc2si+ZNS83HOqIpTAY4Vr1SS3bwN1waAiLWCFQYTO4nLaGV0qf8X54FO5YMA//A2Q/yCRjKjTbgrCURXKPtRfZ/CruZZTccVyIE1MozWCODADu6lUqes6V+ziW9YqENv9UfNfQhdTd48=
