language: node_js
node_js:
- 10.9.0
cache: npm
before_install:
- ls -la
notifications:
  slack:
    secure: jIGBHY+b45geMwTvLmR1HbgMLof49QPKlbVFIQMIaE+6TqegLKwBsdMptul3WgV3CdyEb8IVcbkeq8P+PTMXAt/Ee0e+5gBxKdIr4ZaceMJh5sK8XHtCOwl5qUNS/6kgzZLz6QJKiYfAdRtwoQzJMEPfUmIO0MIl5SyMedFIXed2yW7JeJGPPF05yktnxAKed6y529aCqjeRuHhlRfEVM5be8QrjtJ1i/BqqWxZG1jgLXKQRC6hN5dxrv3/6nk7M+RYAfXMT58ChIZ+r/eOff87K0Hlz9xVFsAHewg4k5cYPT2qfdIh8IB4dfgqbfkDmuycAksEACnI9GgWmIP8hi9NAU+zmBhZn4JgjsiAVZ005yVaX63e4rUn3D4c7KXnhxnV//phwzLmq1WOI2InNPs4RwcbWppyf2s6asoFk7drw4Wp46DbfghLb+/6uaM9vN+uWAmbLfZ/TprGNN1qvUR9V5tSV6AV1yTRRLUk9mUFckpzy75cs66rjHBJRfYkyLrxY4Ba2q25wIO2LBPo5p6gvqASa6dRgcnF7iyJ7Ye++wh84U9CkVPRo1gJE2wKn9yYNehC/RjGiRBuA7bp7rfjzHdvpGSxKsKKHFhXeft2i7EfqBtLzemvLD2BlpwkHb8+kmndY53ULza6CWBntdThwk3QU9MOiHDKL1Y6xtOw=
