language: node_js
node_js:
- 10.9.0
cache: npm
before_install:
- ls -la
notifications:
  slack:
    secure: RyVKhVYORApFpGevnzyDQU7qXD7Wu2VHe4tXYlUtU8aw5ZfKjRnKastJZN27hkqqDCIVi+erttStL5ykjw9ubdnqoSOwUkd20Gy0pvitqG//SV+Hi3HOuQFTXgCybCOzGqPhEpdkL6fOt6fTCc1c36HzoziytLyJZGHLEl75ewqqyCrYdZitpJp3ay9mPIl1iJ0/8KDDs9djmYWozunZGcII7EuFPdH2Aqt+b1ocYXoAG+6GbautcC5ljEp2dTLVFjJBllbWn/RgP7Zo1Kw+jF3X5Qqm0naVqsUVAkXfdlj9r8yohqf/v4IjM5jS5tnlgRu5LAsQfTJAdRJN/GfK8zNzc1hy57ZY9FD2QJGKwE8XFLfBQ0K1cF4WIOXWIber5m3Uu9GQSTXy+rJx/19fJhLdTwLofcWRhcMP+SpzFrRfVptXNHYlPiQLr/wLCpUl6EVUpj+ZUAXhA1NvQvXnULSzHuyHlLvQCkUOx0RJtjlUZjTJ3Z5q7lqiaA71udD8slJkjwrBxVZlt5YwlzlwsQf4zz1WdlZ342aT3GqKy1O4Z4yugwDzw3xwMRlbaFdpgqfYnjf9E72sxFSmWDEYjrafQ7Z4g3RrqGzpvZESvpuBNu48YePI17JRiO9W7zFVyYfnJO8V2PX6ZfONjgeS1fBJbVurahBJ3SGqii3OeeU=
