language: node_js
node_js:
  - 10.9.0
cache: npm
before_install:
  - ls -la
notifications:
  slack:
   rooms:
      secure: cGcOpR2F7/L3HyGDpJBrpWMoQzSepwOLycfk/6qGBkmHV9euO7JU88uniDunvIlZPJFfWtuJAAGTEd0624GvTAE9uA21Gjdc0eFSt5hRiEInzl7Ak3/v11CNikeEH0Ju7igmA64kchkLWqVm2GKGre6Tph8Ix7QUH139xROll+kJNJg92RiMoPeeyJwjrA1OF09+BKTxN5fYDgd/0/TkXBR2YYgS8uSdBexg9s0aZkYMYrTHVfg8UquWOHHl4NXPJOb3xQyX5sk/Wb8mGqdnk8byshCZE3ChVICp7SyV4ohP9mZWn+plutSEpmKC1JCNNtBia7bmo1EP9u7GccEn0BnnXhzb3x/91QfDyAYWT7LEgvTuanxJv98MKW1Q7d+l1Z4EQIt+UCuPArGjY66KzEbjOoTnW3rs2f0PzHukZ+zgZzoOrcF22uAVM03BTocHg4jFPEMsbJnFiLU+nT8g67nnS+8Wt9gL+3qibZpFtfgFeBfMg9zZGO3GYIsZPGAFRx4H/nm9Ea/td3vZx1/6YobWcx1Bc/SdE6W0XeGoOTOl8tfCzIZ9mjxWxyxabXzZxpyklD1WqUhhqNVJ3+1jTiAaQUplZZteblGD00K//Q0wwVx6AVauCCMV4co8+PHNnYbfoK68EIM6aAK3wateVc+C8WGrWr4C0atPu3dvKk8=
