language: node_js
node_js:
  - 10.9.0
cache: npm
before_install:
  - ls -la
notifications:
  slack:
    secure: ffVdmFMmJkq2u+Nuvsupcjf0JBON6vRSOjq6t+OtUqQtA1Y1JKriLZQzromLXsxrt/Uq0Lrf6tn0s3v/1tvNDMHkLim5U2KX67K1P0VspprrV64JImqVhxU+OQyb/OehL5SOYxUKPqjO8hF7/3HClnesKBKk/AozeHQr2+g5AZ7bBIXb3JrubYjed3zzUJ8jeJkf2EgeMqE2DwfC0AUNq5nTeRZDuOLjqmHWbVFD1OiWfuePz049I8reMkzrCeZOU91uz1TUXzdKQCwdWYAx/oxQdOw7jMJ25vOh+90R/AW7vfsMCOOaPoLq1fsFyV6bhQBKYuXwK1N6RPfQhE8Eg/3RqLDDk2NWV7b7fhQDoFLq69eA1YPvC5Df9a3MDV4wya2gLtNeskJ/VOBzbiiuq2q37jr17WEh8sK6vuhQrQh9PAqDe/Qk9XWrElQdt7JTNDftsHM6au5yBCqOiYNlvCEub9FNK28889S1H42mnpEOYoYau1mx+eCisFvQefsjm2V4S9yRZ0iDO16n3W2VBhlM60oLig+L3IozxBnjO4EckfHMMnz6cF+LY4g8u60ycjQFq88dMaofBA+cCQmL/Uj4XzX1xYj6hwn743CUv3ZCd+eVfBxM0kZFxGFwbvs9PNSgQl/uUjoOEXOfruNmr4N9rzSK7Eh9WA1tJ9Dg0o8=
