language: node_js
node_js:
  - 10.9.0

cache: npm

before_install:
  - ls -la

notifications:
  slack:
    rooms:
      - secure: "wuXSM6277aYlD5CDa6wiV0jo0RhkgWNT7LBz7LCIpFwToER7hsC6tQvT4Ck4YtTOyvXvsCAUmBtGTCQZATY7fKZ1FeeelW3EE2qXtQc6KJq3IY7TEtCO3sYitNdbSN99WBNCXP3Ab/yOrYuID6pKLOiq7PAU1eRBHOTqJH1LNhiy0ssi+NlQOz0OBj4+VXt6JiwHWjNZ98+GxUc/mKetLtBv87nj2b6eoUfFlmJr2hddjptd30/ySLxZWjvltIEAZFq1DWztJ+lCoMUsrzjz2Mag2tSFMIA2mivFxNGtx5zetIcKetBKHbYwc8FCDbPd7BUwczVq9OjuTPmzgP6Ejf3JXOAAqaND14tcmHIxpFDA8me7ws1Af5qhHgvzDouu5WHWXv1UTsXeJPmYggpokcDKP8YUtpOA9uSi4iDmk/2FzEEVTcCzt0JNV/jJjM7xRH54fl1JMMn9qpIeKy8Q+cpe7NNtwmo0KcrRoD1JSPR17AISJODimYfb77WhGpMYFUvW6BsLCcdwgm4w4ynhw7dX6hCWdpcHLj3nX96pm9yYENq0HA6/BCZ5+s7lsYMhRcCSnKmtAQZ4eopny2n+1IY2/tvLHKjZW4kiCiFZRjoPE4QaYKlF+y7Utcp1eYZ/hjgjay9/qKct71UgzHwe8iqz1i+OZWo8Y7tHb074qEc="
    on_success: always