language: node_js
node_js:
- 10.9.0
cache: npm
before_install:
- ls -la
notifications:
  slack:
    if: branch = master
    rooms:
      secure: vT2pGGo8wQc83a+nxHQLkXPNw0cZntM5xhI1mFyh1zSdQyYmTdW96hbAB6UE4xIESMfrdall9qcC7jdbEcBHKqnmpAUM7LAuuSnVFU7khbJkHEFqYOBm385W5/xIXC+KkvtHFQaBIm6n74H/0MOos5TxlCzJhSUSW35cWcr0fgkb7OPFZwJFfUn9hSbFlz5BdZn+aCWLLm58D333QLX4IDFWnmWbxB+jbXQH09zB2+vSp2XVPFpyR/a9o872TXxeRwVokN+hMchEQbfWkaCksBOSsHiK8gcM5OLB4OGb2sDn4lYcwJ+/brvh1n6oB4a4X/EewE3DamOntKVPjVYYUM4Kvmhy3jLESX5IDAWv1f8naSvdFGQQSItQ5gtV7V7FtsciFELKuHaUoR8WIJeaebS88Ufnn3/cJu4jGR45qwTIweEj8n340A2kUqZ4ZOzg0NuSVdBO6umA2XhKBc+JvXBlCp0K44pPDayvV4HYqD2pIcOn6t2v2nc/SayiLjMLWMQFbt++G3Fbr/2z31+wygWwHzsPPf4m1R7gSzH1DjmCK/tKiC8rdfGGToKodzbgDRx6gMxKPJs577doEzWr23v+aMpiWMSnJuym2NoTM7sEhZIPLRgOSuTTBEPZLUMHPGEvRkZOon30yIUmTEtUdK+ZeKYw4zA+yRYApxpW3fk=
