language: node_js
node_js:
- 10.9.0
cache: npm
before_install:
- ls -la
notifications:
  slack:
    rooms:
      - secure: 1BRUzR1NMfHH8VPIhZmJcFwJ4nXgoUq+nY/gWsVnRXNYJGfNxBZrvXpUht409304wU6CxjrqWMGppZ60iWIRHK+yeuI/IC7u4ucAGWClbbht7wLA9DGfW/SsrapLrYWUlLWPQAvGTVYrS25760+AwAtScMzIpGTS+Vo9ePaW0XgZTnYcCNH/21u1fYndSeliDxryKDlpYfaJCPm7AJhUqeZtLenvTuBhQhZDtLzhO617DHtI6QX4rx/fXtLOhr1T/oWk2aVj1z3S07x5qb7iX27vcsdrKSEce0M+jokXejCig9Kdcad7Klkmiw4jZuexq3CNBmGwbBNsnRr6WrY6r/sO1IF6CfdKH4pB4QcXZkAgCLaPYwaiQc0zsePibGNf4oXLP41A71OS2PuUjr8AbW4MJdsSenhcNEpmUTrPkVJOm00ffC1aVQxpWIUDxo/ZiyI8CFOlqc899uTsPdoc1Yhj3TBKESJtAbgHjlSzVRkQURh5i2qQYI2XGjNt0yH72JolYU0AgfVgHBNpT7lUawTh7btzAOP0Y2TI4y6p0RVvRuMAieCG15on8zZBImT12HxIYpXVgHOLsQWKs+fD4Vex3aDkfkJKMdcU4ZcO9Xf94wkDchSSMn4IZbZzGalI9lBWI/TNbyHdSAtLzmfDzzVMAW3jiu+/dNXfAYhkXM8=
      on_success: always
      on_failure: always
