language: node_js
node_js:
- 10.9.0
cache: npm
before_install:
- ls -la
notifications:
  slack:
    secure: 6bd43ytRCG+LStaDBnXn28572eZqD6jAnxD7krfy7lyC2YJCPVkgJugKk5A9I5kRlbQvVRk2v1Lp8D/1Vh3BcW4JwiCHQpLA0ykP+DaZXPmOxPZTkuqDofT3FHYAzBaCxIp6kVkDikz7tBJDOK82k+Hon+4CCJFhYsSZBOvHjunAteio9sqp+ThaVbghohWUahEXoAqZxW+QGZA1G0U8u7j+nryNSIl5s8BgBN2wfWL9j7xKvgANoQxT0ee1qfzNOqevyj/aYlYcpk2U7QubLso0EecJ9q4yTGXAGHNtI4uTCNtuqzQ4WQ2cbDlnLZcIVYnf3V6Vqnucw5/vlGuDrx5wcJlaKgBFLHR3RFA/PAjZiepz4Ed3fI50Hc0ZNjKD/s3pBykaoh/KFEQNUKmPkZsPpjgsIfFflH0aE0Gr44ErKAq6Gd29y+yMk7Jd1Zu165fCbCsv2qmHjCDOwVNI5vOwy0HkCcxq0IMS7vMLb16+Rmqx9GQm5srwYG51AKqMVr36OZG6y+prxVSanMtzuRD3gwrzNdlZdm2u8gHW6J4oz0+uGH7QXIrlZfmRa6e6RVjtTlYOxoovpCYDDddAqkcF89YHnM5BgmsUbhP5KzUjlkpHetE8TGtwViPkAZlWAG/q54l+5CqU91mj9a9rsg7OgPmEe40bwJH/iOMOFi4=
